# - Try to find Ogre
# Once done this will define
#  
#  OGRE_FOUND        - system has Ogre
#  OGRE_INCLUDE_DIR  - the Ogre include directory
#  OGRE_MAIN_LIBRARY   - Path to OgreMain Library


FIND_PATH(OGRE_INCLUDE_DIR Ogre.h /usr/include/OGRE /usr/local/include/OGRE)

FIND_LIBRARY(OGRE_MAIN_LIBRARY OgreMain /usr/lib/OGRE)

IF(OGRE_INCLUDE_DIR AND OGRE_MAIN_LIBRARY)
	SET(OGRE_FOUND TRUE)
ENDIF (OGRE_INCLUDE_DIR AND OGRE_MAIN_LIBRARY)

IF(OGRE_FOUND)
	IF(NOT OGRE_FIND_QUIETLY)
		MESSAGE(STATUS "Found Ogre: ${OGRE_MAIN_LIBRARY}")
	ENDIF(NOT OGRE_FIND_QUIETLY)
ELSE(OGRE_FOUND)
	IF(OGRE_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could not find Ogre")
	ENDIF(OGRE_FIND_REQUIRED)
ENDIF(OGRE_FOUND)
